export const mockAboutMe = {
  name: 'Nicolás Recalde Ledesma',
  headline: 'Ingeniero de Software',
  bio: [{ children: [{ text: 'Estudiante de Ingeniería de Software con experiencia práctica en desarrollo Full-Stack, arquitectura de sistemas y gestión de bases de datos. Especializado en la creación de soluciones tecnológicas eficientes, con dominio en el desarrollo de aplicaciones web (React, Next.js), diseño de APIs (Flask, Node.js) y modelado de datos relacionales y NoSQL.' }] }],
  location: 'Quito, Ecuador',
  cvUrl: '#',
  socialLinks: { github: 'https://github.com/nirec1810' },
}

export const mockSkills = [
  { name: 'Python',       category: 'languages', proficiency: 'advanced', order: 1 },
  { name: 'C#',           category: 'languages', proficiency: 'advanced', order: 2 },
  { name: 'JavaScript',   category: 'languages', proficiency: 'advanced', order: 3 },
  { name: 'TypeScript',   category: 'languages', proficiency: 'advanced', order: 4 },
  { name: 'SQL',          category: 'languages', proficiency: 'advanced', order: 5 },
  { name: 'React.js',     category: 'frontend',  proficiency: 'advanced', order: 6 },
  { name: 'Next.js',      category: 'frontend',  proficiency: 'advanced', order: 7 },
  { name: 'HTML5',        category: 'frontend',  proficiency: 'advanced', order: 8 },
  { name: 'CSS3',         category: 'frontend',  proficiency: 'advanced', order: 9 },
  { name: 'ASP.NET Core', category: 'backend',   proficiency: 'advanced', order: 10 },
  { name: 'Node.js',      category: 'backend',   proficiency: 'intermediate', order: 11 },
  { name: 'Flask',        category: 'backend',   proficiency: 'intermediate', order: 12 },
  { name: 'Entity Framework Core', category: 'backend', proficiency: 'intermediate', order: 13 },
  { name: 'SQL Server',   category: 'databases', proficiency: 'intermediate', order: 14 },
  { name: 'PostgreSQL',   category: 'databases', proficiency: 'intermediate', order: 15 },
  { name: 'MySQL',        category: 'databases', proficiency: 'intermediate', order: 16 },
  { name: 'MongoDB',      category: 'databases', proficiency: 'intermediate', order: 17 },
  { name: 'Supabase',     category: 'databases', proficiency: 'intermediate', order: 18 },
  { name: 'Microsoft Azure', category: 'devops', proficiency: 'intermediate', order: 19 },
  { name: 'Docker',       category: 'devops',    proficiency: 'intermediate', order: 20 },
  { name: 'Jenkins',      category: 'devops',    proficiency: 'basic', order: 21 },
  { name: 'CI/CD Pipelines', category: 'devops', proficiency: 'basic', order: 22 },
  { name: '.NET MAUI',    category: 'mobile',    proficiency: 'intermediate', order: 23 },
  { name: 'Flutter',      category: 'mobile',    proficiency: 'basic', order: 24 },
  { name: 'Git',          category: 'tools',     proficiency: 'advanced', order: 25 },
  { name: 'GitHub',       category: 'tools',     proficiency: 'advanced', order: 26 },
]

export const mockProjects = [
  {
    title: 'EcoShelf Analytics',
    slug: 'ecoshelf-analytics',
    description: 'Plataforma integral para la gestión de excedentes alimentarios en panaderías. Motor de sugerencias y analítica de inventario en tiempo real.',
    longDescription: [
      { children: [{ text: 'Proyecto más complejo del portfolio — arquitectura limpia, patrones de diseño, full-stack moderno y dominio de negocio real con reglas concretas. Construida con Next.js 15, TypeScript y Supabase.' }] },
      { children: [{ text: 'Incluye autenticación con Supabase Auth y protección de rutas via src/proxy.ts. Dashboard con KPIs, alertas de vencimiento y análisis de rentabilidad.' }] },
    ],
    year: 2026,
    featured: true,
    tier: 5,
    primaryLanguage: 'TypeScript',
    architecture: 'MVC + Facade Pattern',
    techStack: [
      { tech: 'Next.js', role: 'Framework full-stack' },
      { tech: 'TypeScript', role: 'Lógica y tipos' },
      { tech: 'Supabase', role: 'Auth + PostgreSQL' },
      { tech: 'Tailwind CSS', role: 'Estilos' },
      { tech: 'SOLID + Facade Pattern', role: 'Arquitectura del motor' },
    ],
    highlights: [
      { item: 'Motor de sugerencias modular bajo src/controllers/motor/ (SOLID, 6 archivos, Facade como entry point)' },
      { item: 'Patrón MVC con naming conventions en español' },
      { item: 'Dashboard con KPIs, alertas de vencimiento y análisis de rentabilidad' },
      { item: 'Autenticación con Supabase Auth y protección de rutas' },
    ],
    links: { github: 'https://github.com/nirec1810/ecoshelf-analytics' },
  },
  {
    title: 'Mejores Prácticas',
    slug: 'mejores-practicas',
    description: 'Aplicación web ASP.NET Core MVC con implementación de patrones de diseño GoF: Singleton, Repository, Builder y Factory Method.',
    longDescription: [
      { children: [{ text: 'Implementación práctica de patrones de diseño GoF en el ecosistema .NET. Cada patrón está aplicado en un contexto real y documentado con su uso correcto.' }] },
      { children: [{ text: 'Incluye Singleton para acceso a base de datos, Repository para abstracción de datos, Builder para construcción de objetos complejos y Factory Method para creación de instancias.' }] },
    ],
    year: 2026,
    featured: true,
    tier: 5,
    primaryLanguage: 'C#',
    architecture: 'Patrones GoF en ASP.NET Core',
    techStack: [
      { tech: 'ASP.NET Core MVC', role: 'Framework web' },
      { tech: 'C#', role: 'Lógica y patrones' },
      { tech: 'Design Patterns (GoF)', role: 'Arquitectura' },
    ],
    highlights: [
      { item: 'Implementación de Singleton, Repository, Builder y Factory Method' },
      { item: 'Patrones aplicados en contexto real, no ejemplos aislados' },
      { item: 'Proyecto más reciente del portfolio (Junio 2026)' },
    ],
    links: { github: 'https://github.com/nirec1810/Mejores_practicas' },
  },
  {
    title: 'MinicoreMVC',
    slug: 'minicoremvc',
    description: 'Sistema de cálculo de costos de envío por repartidor con Next.js 15 y Supabase, implementando el patrón MVC end-to-end.',
    longDescription: [
      { children: [{ text: 'Implementación completa del patrón MVC con Next.js 15 y Supabase. Tablas repartidores, envios y zonas en la base de datos PostgreSQL de Supabase.' }] },
      { children: [{ text: 'Deploy automático en Vercel. Incluye CRUD completo con manejo de estados y validaciones.' }] },
    ],
    year: 2026,
    featured: true,
    tier: 5,
    primaryLanguage: 'TypeScript',
    architecture: 'MVC end-to-end',
    techStack: [
      { tech: 'Next.js', role: 'Framework full-stack' },
      { tech: 'TypeScript', role: 'Lógica y tipos' },
      { tech: 'Supabase', role: 'Base de datos + API' },
      { tech: 'Vercel', role: 'Deploy' },
    ],
    highlights: [
      { item: 'Patrón MVC implementado end-to-end' },
      { item: 'Tablas repartidores, envios y zonas' },
      { item: 'Deploy en Vercel' },
    ],
    links: { github: 'https://github.com/nirec1810/MinicoreMVC' },
  },
  {
    title: 'Hotel Room Booking',
    slug: 'hotel-room-booking',
    description: 'Aplicación web MVC completa para reserva de habitaciones de hotel con Entity Framework Core Code First.',
    longDescription: [
      { children: [{ text: 'Sistema CRUD funcional de reserva de habitaciones de hotel con patrón MVC completo sobre ASP.NET Core. El esquema de base de datos se genera desde las clases C# mediante Code First con Entity Framework Core.' }] },
      { children: [{ text: 'Incluye validaciones de modelo, manejo de estados y vistas Razor con HTML/CSS/JS integrado. 11 commits que reflejan un desarrollo iterativo real.' }] },
    ],
    year: 2025,
    featured: false,
    tier: 4,
    primaryLanguage: 'C#',
    architecture: 'ASP.NET Core MVC + Code First',
    techStack: [
      { tech: 'ASP.NET Core MVC', role: 'Framework web' },
      { tech: 'Entity Framework Core', role: 'ORM + migraciones' },
      { tech: 'C#', role: 'Lógica' },
      { tech: 'Razor', role: 'Plantillas' },
      { tech: 'HTML', role: 'Estructura' },
      { tech: 'CSS', role: 'Estilos' },
      { tech: 'JavaScript', role: 'Interacciones' },
    ],
    highlights: [
      { item: 'CRUD completo con validaciones de modelo' },
      { item: 'Code First con Entity Framework Core' },
      { item: 'Vistas Razor con diseño responsivo' },
    ],
    links: { github: 'https://github.com/nirec1810/NicolasRecaldeEvaluacionProgreso1' },
  },
  {
    title: 'Ecommerce',
    slug: 'ecommerce',
    description: 'Arquitectura de microservicios para un sistema de e-commerce. Cada módulo es independiente y desplegable por separado.',
    longDescription: [
      { children: [{ text: 'Sistema de e-commerce con arquitectura de microservicios usando Spring Boot y Java 17. Cada módulo es independiente y desplegable por separado.' }] },
      { children: [{ text: 'También existe una versión refactorizada en Ecommerce-. Arquitectura orientada a servicios con comunicación entre módulos.' }] },
    ],
    year: 2026,
    featured: true,
    tier: 4,
    primaryLanguage: 'Java',
    architecture: 'Microservicios con Spring Boot',
    techStack: [
      { tech: 'Spring Boot', role: 'Framework de cada microservicio' },
      { tech: 'Java', role: 'Lenguaje principal' },
      { tech: 'Microservicios', role: 'Diseño del sistema' },
    ],
    highlights: [
      { item: 'Arquitectura de microservicios independientes' },
      { item: 'Cada módulo desplegable por separado' },
      { item: 'Versión refactorizada disponible' },
    ],
    links: { github: 'https://github.com/nirec1810/Ecommerce' },
  },
  {
    title: 'ArquitecturaC4',
    slug: 'arquitecturac4',
    description: 'Consulta de datos de contribuyentes, vehículos y licencias desde los servicios públicos de Ecuador (SRI y ANT) con Arquitectura C4.',
    longDescription: [
      { children: [{ text: 'Backend en Spring Boot y Java para consumir APIs del SRI y ANT de Ecuador. Frontend en React para la visualización de datos de contribuyentes, vehículos y licencias.' }] },
      { children: [{ text: 'Documentación arquitectural completa usando el modelo C4 (Contexto, Contenedor, Componentes, Código). Modelo de datos y flujos de información bien documentados.' }] },
    ],
    year: 2025,
    featured: false,
    tier: 4,
    primaryLanguage: 'Java',
    architecture: 'C4 Model + Spring Boot + React',
    techStack: [
      { tech: 'Spring Boot', role: 'Backend REST' },
      { tech: 'Java', role: 'Lenguaje principal' },
      { tech: 'React', role: 'Frontend' },
      { tech: 'C4 Model', role: 'Documentación arquitectural' },
      { tech: 'SRI / ANT APIs', role: 'Fuentes de datos externas' },
    ],
    highlights: [
      { item: 'Consumo de APIs públicas del SRI y ANT de Ecuador' },
      { item: 'Documentación C4 completa (Contexto, Contenedor, Componentes)' },
      { item: 'Backend Spring Boot + Frontend React' },
    ],
    links: { github: 'https://github.com/nirec1810/ArquitecturaC4' },
  },
  {
    title: 'Voxline',
    slug: 'voxline',
    description: 'Aplicación de chat en tiempo real usando WebSockets — comunicación bidireccional persistente entre cliente y servidor.',
    longDescription: [
      { children: [{ text: 'Sistema de chat en tiempo real con WebSockets. Comunicación bidireccional persistente entre cliente y servidor sin polling. Implementación completa del protocolo WebSocket.' }] },
    ],
    year: 2026,
    featured: false,
    tier: 4,
    primaryLanguage: 'HTML/JS',
    architecture: 'WebSocket real-time',
    techStack: [
      { tech: 'HTML', role: 'Estructura' },
      { tech: 'JavaScript', role: 'Lógica WebSocket' },
      { tech: 'WebSockets', role: 'Comunicación en tiempo real' },
    ],
    highlights: [
      { item: 'Comunicación bidireccional persistente' },
      { item: 'Sin polling — WebSockets nativos' },
    ],
    links: { github: 'https://github.com/nirec1810/Voxline' },
  },
  {
    title: 'RecaldeNicolasPeople',
    slug: 'recaldenicolaspeople',
    description: 'App multiplataforma .NET MAUI con SQLite asíncrono para persistencia local. CRUD completo con sqlite-net.',
    longDescription: [
      { children: [{ text: 'Implementación del módulo oficial de Microsoft sobre almacenamiento local en .NET MAUI. Persistencia con SQLite usando sqlite-net y operaciones asíncronas.' }] },
    ],
    year: 2025,
    featured: false,
    tier: 4,
    primaryLanguage: 'C#',
    architecture: '.NET MAUI + SQLite Asíncrono',
    techStack: [
      { tech: '.NET MAUI', role: 'Framework multiplataforma' },
      { tech: 'C#', role: 'Lógica' },
      { tech: 'SQLite', role: 'Persistencia local' },
      { tech: 'XAML', role: 'UI' },
    ],
    highlights: [
      { item: 'Implementación del módulo oficial de Microsoft' },
      { item: 'SQLite asíncrono con sqlite-net' },
      { item: 'CRUD completo multiplataforma' },
    ],
    links: { github: 'https://github.com/nirec1810/RecaldeNicolasPeople' },
  },
  {
    title: 'maquinasInterpretacion',
    slug: 'maquinas-interpretacion',
    description: 'Sistema que instancia cualquier figura geométrica usando reflexión de Java — sin conocer el tipo en compilación.',
    longDescription: [
      { children: [{ text: 'Sistema que instancia cualquier figura geométrica a partir del nombre de clase y parámetros en tiempo de ejecución usando reflexión de Java.' }] },
      { children: [{ text: 'Ejemplo: ("Circulo", radio=5) crea el objeto y calcula área/perímetro dinámicamente — sin conocer el tipo en compilación.' }] },
    ],
    year: 2025,
    featured: false,
    tier: 4,
    primaryLanguage: 'Java',
    architecture: 'Reflexión de Java',
    techStack: [
      { tech: 'Java', role: 'Reflexión y lógica' },
    ],
    highlights: [
      { item: 'Reflexión de Java para instanciar clases en tiempo de ejecución' },
      { item: 'Concepto avanzado que va más allá del desarrollo universitario típico' },
    ],
    links: { github: 'https://github.com/nirec1810/maquinasInterpretacion' },
  },
  {
    title: 'Principios de Diseño',
    slug: 'principios-de-diseno',
    description: 'Implementación del patrón Proxy para controlar el acceso a un objeto real y diferir su creación.',
    longDescription: [
      { children: [{ text: 'Implementación del patrón Proxy para controlar el acceso a un objeto real y diferir su creación (lazy initialization). Demuestra el principio de design by contract.' }] },
    ],
    year: 2025,
    featured: false,
    tier: 3,
    primaryLanguage: 'HTML/JS',
    architecture: 'Patrón Proxy',
    techStack: [
      { tech: 'HTML', role: 'Estructura' },
      { tech: 'JavaScript', role: 'Implementación del Proxy' },
    ],
    highlights: [
      { item: 'Patrón Proxy con lazy initialization' },
      { item: 'Control de acceso a objetos' },
    ],
    links: { github: 'https://github.com/nirec1810/Principios-de-Diseno' },
  },
]

export const mockExperience = [
  {
    company: 'EcoShelf Analytics',
    role: 'Desarrollador Full-Stack',
    description: 'Optimicé la gestión de excedentes de alimentos para panaderías, consolidando el flujo de datos en paneles de inteligencia de negocios.',
    highlights: [
      { item: 'Desarrollé una arquitectura escalable utilizando Next.js (React) y Supabase' },
      { item: 'Implementación de microservicios e integración de APIs REST' },
      { item: 'Integración de Unity para desarrollo 2D/3L y ciberseguridad (OSINT, Wazuh)' },
    ],
    startDate: '2024-01-01',
    endDate: '2024-06-30',
    current: false,
    order: 1,
  },
  {
    company: 'Sistema de Gestión',
    role: 'Ingeniero de Software Back-End',
    description: 'Centralicé el control de asistencia y registro de familias, eliminando la pérdida de datos manuales a través de un sistema de gestión CRUD.',
    highlights: [
      { item: 'Programé la lógica de servidor en Python (Flask)' },
      { item: 'Integración con base de datos relacional en SQL Server' },
      { item: 'Eliminación de datos manuales mediante sistema CRUD automatizado' },
    ],
    startDate: '2024-01-01',
    endDate: '2024-06-30',
    current: false,
    order: 2,
  },
  {
    company: 'World Hackathon',
    role: 'Desarrollador Frontend',
    description: 'Aceleré la entrega técnica del prototipo durante la competencia, mediante la implementación de componentes reutilizables.',
    highlights: [
      { item: 'Implementación de componentes reutilizables y hooks' },
      { item: 'Consumo de APIs REST con React' },
      { item: 'Control de versiones con Git/GitHub' },
    ],
    startDate: '2024-01-01',
    endDate: '2024-02-28',
    current: false,
    order: 3,
  },
]

export const mockEducation = [
  {
    institution: 'Universidad de las Américas (UDLA)',
    degree: 'Ingeniería en Software — 7° semestre',
    description: 'Carrera en curso desde 2023. Enfocada en desarrollo Full-Stack, arquitectura de sistemas y gestión de bases de datos.',
    startDate: '2023-09-01',
    current: true,
    order: 1,
  },
  {
    institution: 'Liceo José Ortega y Gasset',
    degree: 'Bachillerato General Unificado',
    description: 'Educación secundaria en Quito, Ecuador.',
    startDate: '2013-09-01',
    endDate: '2022-06-30',
    current: false,
    order: 2,
  },
]

export const mockCertifications = [
  { name: 'DevOps de cero a experto',            category: 'cloud-devops',  date: 'Oct 2025',  platform: 'Udemy',     order: 1 },
  { name: 'Terraform - Infraestructura como código', category: 'cloud-devops',  date: 'Dic 2025',  platform: 'Udemy',     order: 2 },
  { name: 'DevOps de cero a avanzado',           category: 'cloud-devops',  date: 'Dic 2025',  platform: 'Udemy',     order: 3 },
  { name: 'Master ASP.NET MVC - Entity Framework (.NET 9)', category: 'backend-mobile', date: 'May 2025', platform: 'Udemy', order: 4 },
  { name: '.NET MAUI con Visual Studio 2022',   category: 'backend-mobile', date: 'Jun 2025',  platform: 'Udemy',     order: 5 },
  { name: 'Flutter & Dart iOS, Android y móvil', category: 'backend-mobile', date: 'Jun 2025',  platform: 'Coursera',  order: 6 },
  { name: 'React 18 Course 2025',                category: 'frontend',      date: 'May 2025',  platform: 'Udemy',     order: 7 },
  { name: 'Python - Data Structures & Algorithms + LeetCode', category: 'fundamentals', date: 'Nov 2024', platform: 'Udemy', order: 8 },
  { name: 'Software Processes and Agile Practices', category: 'soft-skills', date: 'Jun 2023',  platform: 'Coursera',  order: 9 },
  { name: 'Understand & Elicit Requirements with Business Analysis', category: 'soft-skills', date: 'Nov 2024', platform: 'Udemy', order: 10 },
  { name: 'Communication Skills: Improve Communication', category: 'soft-skills', date: 'Abr 2023', platform: 'Udemy', order: 11 },
]

export const mockLanguages = [
  { name: 'Español',                proficiency: 'Nativo',          order: 1 },
  { name: 'Inglés',                 proficiency: 'Intermedio-Avanzado (B2)', order: 2 },
]

export const mockData: Record<string, any[]> = {
  'about-me': [mockAboutMe],
  projects: mockProjects,
  experience: mockExperience,
  skills: mockSkills,
  education: mockEducation,
  certifications: mockCertifications,
  languages: mockLanguages,
}